### ISSUE TITLE
don't update to .34

### ISSUE THREAD

**Issue by bigbear22941** [Tautulli/Tautulli-Issues#192] opened 2019-09-05 15:15 UTC
Hello...

i'am trying to update Tautulli to v .34...

but this is, was the console says:
```
2019-09-05 17:08:41 - DEBUG :: MainThread : Trying to execute: "git pull origin master" with shell in C:\Program Files (x86)\Plex\PlexPy
2019-09-05 17:08:42 - DEBUG :: MainThread : Git output: From https://github.com/JonnyWong16/plexpy
 * branch              master     -> FETCH_HEAD
Updating 1046b29c..08714436
error: Your local changes to the following files would be overwritten by merge:
        API.md
        CHANGELOG.md
        data/interfaces/default/history.html
        data/interfaces/default/history_table_modal.html
        data/interfaces/default/info.html
        data/interfaces/default/js/tables/history_table.js
        data/interfaces/default/js/tables/history_table_modal.js
        data/interfaces/default/js/tables/libraries.js
        data/interfaces/default/js/tables/user_ips.js
        data/interfaces/default/js/tables/users.js
        data/interfaces/default/library.html
        data/interfaces/default/user.html
        plexpy/__init__.py
        plexpy/config.py
        plexpy/datafactory.py
        plexpy/libraries.py
        plexpy/notification_handler.py
        plexpy/users.py
        plexpy/version.py
        plexpy/webserve.py
Please commit your changes or stash them before you merge.
Aborting
2019-09-05 17:08:42 - ERROR :: MainThread : Unable to update from git: Aborting
```

i have nothing modified on PlexPy...

**Comment by JonnyWong16** [comment] 2019-09-05 15:16
This is not a bug report. This is a support issue.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support

You also did not check the FAQ.

Closing this issue.

**Closed by JonnyWong16** 2019-09-05 15:16 UTC
