### ISSUE TITLE
v2.6.0 - High CPU usage and continual spawning of process when app is stopped on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by rjblake** [Tautulli/Tautulli-Issues#287] opened 2020-11-02 10:02 UTC
**Describe the Bug**
Upgraded from v2.5.6 and noticed that CPU utilization had gone from 0.5% to ~46.5% (continually). Quit the application, but CPU use did not decrease. Ran ps -ef | grep Tautulli from command line and noticed some Tautulli processes still running, with a continuous stream of new PIDs. Only way to kill was to either delete the Tautulli.app file or restart without Tautulli starting on boot. Tried clean install (removed all traces of Tautulli), but behaviour was the same. Tried v2.6.0-beta and same. Went back to v2.5.4 and operation returned to normal. Updated to v2.5.6 and operation remained normal.

**Steps to Reproduce**
Install v2.6.0 on Mac from .pkg file running Mac OS Catalina v10.15.7 (may be same on other versions but cannot test)

**Expected Behavior**
Tautulli loads and CPU utilisation is normal. Quitting the application from menu bar quits all Tautulli processes

**Screenshots**
![Screen Shot 2020-11-02 at 08 56 43](https://user-images.githubusercontent.com/9930554/97854499-ce639800-1cf9-11eb-956c-dbec5a48f382.png)
Peaks shown are when Tautulli v2.6.0 is running. Lows are when v2.5.6 is running

**Relevant Settings**
No change to settings from v2.5.6->v2.6.0 (or virgin clean install with all defaults)

**Tautulli and System Info (see Tautulli settings page)**
- Version: [v2.6.0]
- Git Branch: [master]
- Git Commit Hash: []
- Platform and Version: [Mac OS Catalina 10.15.7]
- Python Version: [3.5.8 (version packaged with the installed app]
- Browser and Version: [Chrome Version 86.0.4240.111 (Official Build) (x86_64)]

**Link to logs (required)**
[Link to logs](https://gist.github.com/rjblake/79f8f3d553b85bf5111bc51e24686bd5)

**Comment by gcoan** [comment] 2020-11-02 12:39
Same.  My mac mini fans were screaming this morning, pegged at 100% usage.

I did play around with the new export feature yesterday.

**Comment by JonnyWong16** [comment] 2020-11-03 03:36
Can you try this `nightly` build to see if the issue is fixed? Click on the "Tautulli-macos-installer" link to download the `pkg`.

https://github.com/Tautulli/Tautulli/actions/runs/342882482

**Comment by rjblake** [comment] 2020-11-03 07:40
I have done a clean install of the nightly build (install over the top of 2.5.6 did not replace the Tautulli.app file). Noted the following (same behaviour as v2.6.0):

- CPU Utilization - remains high (in my case goes from 0.5% -> 46.5% with no activity)
- Quitting Tautulli does not quit completely (as shown below)

`richard@Mac-mini-i3 ~ % ps -ef | grep Tau
  501 54126     1   0  8:32am ??         0:01.68 /Applications/Tautulli.app/Contents/MacOS/Tautulli
  501 54130 54126   0  8:32am ??         0:00.00 (Tautulli)
  501 55061     1   0  8:34am ??         0:00.58 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
  501 55065 55061   0  8:34am ??         0:00.12 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(4)
  501 55067 53960   0  8:34am ttys000    0:00.00 grep Tau
richard@Mac-mini-i3 ~ % ps -ef | grep Tau
  501 54126     1   0  8:32am ??         0:01.68 /Applications/Tautulli.app/Contents/MacOS/Tautulli
  501 54130 54126   0  8:32am ??         0:00.00 (Tautulli)
  501 55103     1   0  8:34am ??         0:00.46 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
  501 55108 53960   0  8:34am ttys000    0:00.00 grep Tau
richard@Mac-mini-i3 ~ % ps -ef | grep Tau
  501 54126     1   0  8:32am ??         0:01.68 /Applications/Tautulli.app/Contents/MacOS/Tautulli
  501 54130 54126   0  8:32am ??         0:00.00 (Tautulli)
  501 55169     1   0  8:34am ??         0:00.70 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
  501 55173 55169   0  8:34am ??         0:00.23 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(4)
  501 55175 53960   0  8:34am ttys000    0:00.00 grep Tau
richard@Mac-mini-i3 ~ % 
richard@Mac-mini-i3 ~ % ps -ef | grep Tau
  501 56370     1   0  8:36am ??         0:00.56 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
  501 56374 56370   0  8:36am ??         0:00.10 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(4)
  501 56376 53960   0  8:36am ttys000    0:00.00 grep Tau
richard@Mac-mini-i3 ~ % ps -ef | grep Tau
  501 56400     1   0  8:36am ??         0:00.50 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(4)
  501 56404 56400   0  8:36am ??         0:00.04 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
  501 56406 53960   0  8:36am ttys000    0:00.00 grep Tau
richard@Mac-mini-i3 ~ % ps -ef | grep Tau
  501 58482     1   0  8:39am ??         0:00.78 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(4)
  501 58489     1   0  8:39am ??         0:00.45 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(4)
  501 58490 58482   0  8:39am ??         0:00.31 /Applications/Tautulli.app/Contents/MacOS/Tautulli -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
  501 58498 53960   0  8:39am ttys000    0:00.00 grep Tau`

**Comment by JonnyWong16** [comment] 2020-11-03 07:56
Make sure you downloaded the correct build. It should be be `e9db43e`. I edited the link about 40 minutes ago.

If it doesn't work, try removing the old `Tautulli.app` before installing the new build.

**Comment by rjblake** [comment] 2020-11-03 10:43
I have tried again with the latest version. Deleted old `Tautulli.app` before installing. Oberservations:

- Installed without problem
- Can shutdown without issue (no spawning processes)
- CPU Utilisation appears to be more normal (will validate over coming hours)

**Comment by JonnyWong16** [comment] 2020-11-04 02:00
Fixed in v2.6.1.

**Closed by JonnyWong16** 2020-11-04 02:00 UTC
Labels: fixed-next-release, severity:critical, topic:server, type:bug
