### ISSUE TITLE
Stream audio Channels variable issue

### ISSUE THREAD

**Issue by sambarlick** [Tautulli/Tautulli-Issues#179] opened 2019-05-29 13:57 UTC
**Version:**
V2.1.30-BETA
**Branch:**
beta
*Commit hash:**
4b744a5acd5bb11c562238bb96b1a3970bdb641d 
**Operating system:**

Windows 10 (10.0.17134)
**Python version:**
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
**What you did?**
Notification to both Tautulli android app and pushbullet when play is triggered. 

Notification is conditional with stream_audio_channels and player
**What happened?**
Stream_audio_channels variable is reporting 2 with multi channel audio. 
Tautulli main page is reporting the files as 5.1 and also stream_audio_channel_layout variable is reporting 5.1.
**What you expected?**
6 channels (5.1). 
**How can we reproduce your issue?**
I have 2 notifications 1 for stereo sound and 1 for surround sound. 

Notification to pushbullet or tautulli phone app triggered by Play. 
(not sure if conditions are required) 
Condition 1
stream_audio_channels is not 2 (for surround notification)
Or
stream_audio_channels is 2 (for stereo notification) 

Condition 2
Player is Mac mini
**What are your (relevant) settings?**

**Link to logs:**
https://gist.github.com/sambarlick/81b52c647cf048144f42b9a6be240fca

**Comment by JonnyWong16** [comment] 2019-05-29 15:09
Which notification triggers?

Streaming notification will use the audio track that is being played.

Recently added notification only grabs the first audio track it finds. This is expected behaviour and not a bug. To change this behaviour would be a [Feature Request](https://github.com/Tautulli/Tautulli-Issues#feature-requests).

**Comment by sambarlick** [comment] 2019-05-29 21:34
I'm sorry, perhaps I wasn't clear.
Whenever something is played in plex I am triggering a notification in tautulli that sends a notification to tautulli android app and pushbullet. 

When the file being played has multi channel audio, eg 5.1, the variable stream_audio_channels = 2 which I am sending in my notification to tautulli app and pushbullet. Plex reports 5.1 audio as does tautulli in the main page.

To test, I also included the variable stream_audio_channel_layout. This variable = 5.1. So plex, tautulli "dashboard" and stream_audio_channel_layout all say the file is 5.1 audio, stream_audio_channels is the only thing I can find stating 2 channels. 

The file is being direct played in plex media player and my app is receiving a 5.1 signal.

What other information can I give you?

**Comment by samwiseg0** [comment] 2019-05-29 21:41
I just tested `{stream_audio_channels}` and it reports the channel number properly. Is that what you are seeing issues with? Can you provide screenshots of what you are seeing?

Keep in mind `{stream_audio_channels}` means the number of audio channels being sent to the player _not_ the source audio channel number.

**Comment by sambarlick** [comment] 2019-05-29 21:54
How do I post screenshots? 

The file is being direct played, there is no transcoding. My amp is receiving multichannel audio.

**Comment by samwiseg0** [comment] 2019-05-29 21:57
You can drag and drop images into the text box. You could also upload them to imgur.

**Comment by Arcanemagus** [comment] 2019-05-29 21:59
Can you also grab the [Activity XML](https://github.com/Tautulli/Tautulli-Wiki/wiki/Debugging#activity) for the stream in question?

**Comment by sambarlick** [comment] 2019-05-29 23:16
XML

<MediaContainer size="1">
<Video addedAt="1556990756" art="/library/metadata/200065/art/1558340221" chapterSource="media" contentRating="TV-14" duration="3042708" grandparentArt="/library/metadata/200065/art/1558340221" grandparentKey="/library/metadata/200065" grandparentRatingKey="200065" grandparentTheme="/library/metadata/200065/theme/1558340221" grandparentThumb="/library/metadata/200065/thumb/1558340221" grandparentTitle="The X-Files" guid="com.plexapp.agents.thetvdb://77398/1/10?lang=en" index="10" key="/library/metadata/200147" lastViewedAt="1559171585" librarySectionID="3" librarySectionKey="/library/sections/3" librarySectionTitle="TV Shows" originallyAvailableAt="1993-11-19" parentIndex="1" parentKey="/library/metadata/200137" parentRatingKey="200137" parentThumb="/library/metadata/200137/thumb/1558340220" parentTitle="Season 1" rating="7.5" ratingKey="200147" sessionKey="35" summary="Mulder puts the future of the X-Files in jeopardy when he heads to a UFO crash site being rapidly covered up by the military. He is arrested, and while in jail he meets Max Fenig, a UFO nut whose NICAP group has followed Mulder's work on the X-Files. When Mulder is released, Scully urges him to return to Washington to face his superiors and try to save his job, but Mulder finds out that Max is more than meets the eye and ignores Scully to try and save him instead." thumb="/library/metadata/200147/thumb/1558340186" title="Fallen Angel" type="episode" updatedAt="1558340186" viewOffset="512000" year="1993">
<Media aspectRatio="1.33" audioChannels="2" audioCodec="aac" audioProfile="he-aac" bitrate="1220" container="mp4" duration="3042708" has64bitOffsets="0" height="504" id="842115" optimizedForStreaming="0" videoCodec="h264" videoFrameRate="NTSC" videoProfile="main" videoResolution="480" width="656" selected="1">
<Part container="mkv" duration="2753130" file="\\Drobo-FS\Drobo\TV Shows\The X Files\Season 01\S01E10 Fallen Angel-part1.mkv" id="994498" key="/library/parts/994498/1454439350/file.mkv" size="1939727911" videoProfile="high" decision="directplay" selected="1">
<Stream bitDepth="8" bitrate="5252" chromaLocation="topleft" chromaSubsampling="4:2:0" codec="h264" colorPrimaries="bt709" colorRange="tv" colorSpace="bt709" colorTrc="bt709" default="1" displayTitle="1080p (H.264)" frameRate="23.976" hasScalingMatrix="0" height="1080" id="2132385" index="0" level="40" profile="high" refFrames="4" scanType="progressive" streamType="1" width="1920" location="direct"/>
<Stream audioChannelLayout="5.1(side)" bitrate="384" channels="6" codec="ac3" default="1" displayTitle="English (AC3 5.1)" id="2132386" index="1" language="English" languageCode="eng" samplingRate="48000" selected="1" streamType="2" location="direct"/>
<Stream bitrate="0" codec="srt" displayTitle="English (SRT)" id="2132388" index="3" language="English" languageCode="eng" selected="1" streamType="3" title="WEB-DL" decision="ignore"/>
</Part>
<Part audioProfile="he-aac" container="mp4" duration="31957" file="\\Drobo-FS\Drobo\TV Shows\The X Files\Season 01\S01E10 Fallen Angel-part2.mkv" has64bitOffsets="0" id="994499" key="/library/parts/994499/1420088083/file.mkv" optimizedForStreaming="1" size="4790745" videoProfile="main"> </Part>
<Part audioProfile="he-aac" container="mp4" duration="257621" file="\\Drobo-FS\Drobo\TV Shows\The X Files\Season 01\S01E10 Fallen Angel-part3.mkv" has64bitOffsets="0" id="994500" key="/library/parts/994500/1420344789/file.mkv" optimizedForStreaming="0" size="39279288" videoProfile="main"> </Part>
</Media>
<Director filter="director=38228" id="38228" tag="Larry Shaw"/>
<Writer filter="writer=17717" id="17717" tag="Alex Gansa"/>
<Writer filter="writer=16609" id="16609" tag="Howard Gordon"/>
<User id="1" thumb="https://plex.tv/users/936f8293d080b35b/avatar?c=1557632934" title="sambarlick"/>
<Player address="192.168.1.41" device="OSX" machineIdentifier="qn9z42mgvzcgrsp5edujcq5m" model="10.13" platform="Konvergo" platformVersion="2.34.0.983-edb7fbf7" product="Plex Media Player" profile="Konvergo" remotePublicAddress="58.107.81.29" state="paused" title="Mac mini" vendor="" version="3.101.2" local="1" relayed="0" secure="1" userID="1"/>
<Session id="gzbsbfs8ld52hurqj3zb8olx" bandwidth="2562" location="lan"/>
</Video>
</MediaContainer>

**Comment by sambarlick** [comment] 2019-05-29 23:19
![tautulli](https://user-images.githubusercontent.com/47462284/58597563-decd4300-82bb-11e9-885f-c222e3aac049.jpg)

**Comment by sambarlick** [comment] 2019-05-29 23:21
![plex](https://user-images.githubusercontent.com/47462284/58597601-0d4b1e00-82bc-11e9-8c28-cf0b2241d36a.jpg)

![pushbullet](https://user-images.githubusercontent.com/47462284/58597641-3a97cc00-82bc-11e9-8209-a70398d06207.jpg)

**Comment by sambarlick** [comment] 2019-05-29 23:25
updated tautulli log file - https://gist.github.com/sambarlick/78a0832370ef0eae3a43d0551f5c9395

**Comment by sambarlick** [comment] 2019-05-29 23:30
I noticed in the xml that it says audioChannels="2" audioCodec="aac" but also channels="6" codec="ac3". Is this plex confusing tautulli?

My amp is defiantly receiving 5.1 audio.

**Comment by Arcanemagus** [comment] 2019-05-29 23:35
> I noticed in the xml that it says audioChannels="2" audioCodec="aac" but also channels="6" codec="ac3". Is this plex confusing tautulli?

Plex is definitely confused here. It looks like you've created a streaming optimized version from the XML, which it seems that Plex is using partially for the information. We're trying to verify what is going.

**Comment by sambarlick** [comment] 2019-05-29 23:53
I haven't created an optimised version. That is the original file. 

Thanks for checking this out guys. I know you've been unable to reproduce the issue but it's really frustrating for me.

**Comment by JonnyWong16** [comment] 2019-05-30 00:31
That looks like one episode in three parts (split into three files). Are one of those three files only 2.0? Maybe Plex takes the lowest number when there are multiple parts.

Anyways, this looks like an issue in Plex and not Tautulli.

**Comment by sambarlick** [comment] 2019-05-30 00:51
Parts 2 and 3 are deleted scenes, both 2.0 audio. I know this is not the correct use of multiple part files.

So the information in tautulli dashboard is from the variable {stream_audio_channel_layout}? 

It's just odd that plex knows it has 5.1 audio but reports it as 2.0 in the stream.

Thanks for your help guys. I think I will have to rethink the conditions of the notification trigger. I'm just not sure how to have the notification text conditional based on whether the stream is direct play or transcoded.

Thanks again.

**Comment by JonnyWong16** [comment] 2019-05-30 00:55
> I know this is not the correct use of multiple part files.

When you use a feature in unexpected ways, you will get unexpected behaviour.

> I'm just not sure how to have the notification text conditional based on whether the stream is direct play or transcoded.

Just use the `{transcode_decision}` parameter...?

Closing this issue since this is not a bug report. If you want further assistance, please use the [Discord Server](https://tautulli.com/discord).

**Closed by JonnyWong16** 2019-05-30 00:55 UTC
