### ISSUE TITLE
Unable to open Newsletter/Notification Agent settings

### ISSUE THREAD

**Issue by zmiguel** [Tautulli/Tautulli-Issues#196] opened 2019-10-02 22:14 UTC
**Describe the Bug**
Unable to change settings for already created newsletter agents or notification agents, once you click the agent a message on the bottom-left corner saying "reading configuration" pops up and nothing happens.

Using the browser console this seems related to a jquery error:

```
Uncaught TypeError: $(...).cron is not a function
    at eval (eval at globalEval (jquery-2.1.4.min.js:2), <anonymous>:3:41)
    at eval (<anonymous>)
    at Function.globalEval (jquery-2.1.4.min.js:2)
    at n.fn.init.domManip (jquery-2.1.4.min.js:3)
    at n.fn.init.append (jquery-2.1.4.min.js:3)
    at n.fn.init.<anonymous> (jquery-2.1.4.min.js:3)
    at n.access (jquery-2.1.4.min.js:2)
    at n.fn.init.html (jquery-2.1.4.min.js:3)
    at Object.complete (<anonymous>:73:47)
    at j (jquery-2.1.4.min.js:2)
```

wich happens once you try to open the agent configuration.

**Steps to Reproduce**
1. Go to 'Settings > Newsletter/Notification Agents'
2. Click on 'already existing agent' or 'add new agent'
3. See error

**Expected Behavior**
window to change agent options shows up and you are able to edit and save settings

**Screenshots**
Not applicable

**Relevant Settings**
None I think.

**Tautulli and System Info (see Tautulli settings page)**
- Version: V2.1.35-BETA
- Git Branch: Beta
- Git Commit Hash: 2cc3e88e6c0830b75ac421b90af989c4c1161b00
- Platform and Version: Debian 10
- Python Version: 2.7.16
- Browser and Version: Chrome Version 79.0.3921.0

**Link to logs (required)**
[Log File](https://gist.github.com/zmiguel/32fe4b8c657edc54b89be132ec9e8a70).

**Comment by JonnyWong16** [comment] 2019-10-02 22:25
Your install is missing files in the `js` folder, or your browser is blocking the javascript files, or your browser cached and old version of the javascript files.
https://github.com/Tautulli/Tautulli/tree/master/data/interfaces/default/js

This is a support issue, not a bug report. If you need support, please use one of our [support options](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support).

Closing issue.

**Closed by JonnyWong16** 2019-10-02 22:25 UTC
