### ISSUE TITLE
Cannot fix metadata on episode, rating key does not change

### ISSUE THREAD

**Issue by Jeeaaasus** [Tautulli/Tautulli-Issues#129] opened 2018-10-07 01:17 UTC
**Version:** v2.1.22
**Branch:** master
**Commit hash:** 03751abc0e34575e2b57d9f0edb241303059ea97
**Operating system:** Linux 3.10.102 (#15284 SMP Mon Jul 9 23:04:14 CST 2018)
**Python version:** 2.7.14 (default, May 28 2018, 14:47:18) 
**Link to logs:** [tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/2453529/tautulli.log)
**What you did?** Tried to use the "Fix Metadata" button on an episode
**What happened?** Nothing
**What you expected?** Expected the rating key to change

**How can we reproduce your issue?**
Unsure.. I'm pretty sure that removing and re-adding files to plex sometimes does this, but it should be possible to simply fix metadata

**Info:**
Some how the info on my jack ryan show got desynced
![image](https://user-images.githubusercontent.com/15081909/46577096-c97a7000-c9dd-11e8-960b-4fe4fc669df1.png)
Here you see 2 different playbacks of the same episode. But if I go to that episode there is only one playback

If I go to the lower of the two, here's how it looks:
![image](https://user-images.githubusercontent.com/15081909/46577104-3130bb00-c9de-11e8-8f28-2a1146a1abee.png)
Only one playback.

If I press "Fix Metadata" and select the correct episode
![image](https://user-images.githubusercontent.com/15081909/46577111-65a47700-c9de-11e8-93db-327336e4b3b5.png)
Everything is fine. But nothing happens, the old rating key does not change.

I did this process and then downloaded the logs.

**Comment by JonnyWong16** [comment] 2018-10-07 01:34
https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs

**Comment by Jeeaaasus** [comment] 2018-10-07 01:44
I did include the logs? 
Link to logs: tautulli.log

**Comment by JonnyWong16** [comment] 2018-10-07 01:56
Step 3.

No one is going to download a file onto their device to look at your logs.

**Comment by Jeeaaasus** [comment] 2018-10-07 02:00
https://gist.github.com/Jeeaaasus/59556ec301c4d757bb062fd247554730

**Comment by JonnyWong16** [comment] 2018-10-07 02:17
Have you actually confirmed the rating key is different on your Plex server?

**Comment by Jeeaaasus** [comment] 2018-10-07 02:31
I'm not sure how I would double check that, how ever let me show some examples.

I just started the episode again and Tautulli sees that:
![image](https://user-images.githubusercontent.com/15081909/46577481-a86b4c80-c9e8-11e8-8179-8df749060d68.png)
3 playbacks

If I click the top or second one (Tautulli Rating key 264112):
![image](https://user-images.githubusercontent.com/15081909/46577502-f2ecc900-c9e8-11e8-803f-e166d403a39c.png)

And the bottom one (Tautulli Rating key 263979):
![image](https://user-images.githubusercontent.com/15081909/46577507-19126900-c9e9-11e8-9b3b-6b84633d1f2f.png)

**Comment by JonnyWong16** [comment] 2018-10-07 02:39
What if you manually go to 

    http://localhost:8181/update_metadata_details?old_rating_key=263979&new_rating_key=264112&media_type=episode

**Comment by Jeeaaasus** [comment] 2018-10-07 02:47
Same message as in the log:
![image](https://user-images.githubusercontent.com/15081909/46577638-8cb57580-c9eb-11e8-87ff-dfc9af2bc889.png)

No change.

I also tried through the api with cmd=update_metadata_details earlier and same result.
updated logs: https://gist.github.com/Jeeaaasus/4b27f5a2a43bb166f5b96d7117215035

**Comment by JonnyWong16** [comment] 2018-10-07 02:51
Try it from the show level.

    http://localhost:8181/update_metadata_details?old_rating_key=XXXXX&new_rating_key=YYYYY&media_type=show

**Comment by Jeeaaasus** [comment] 2018-10-07 02:59
With the same rating keys I tried before:
"Unable to update metadata in database. No changes were made."
![image](https://user-images.githubusercontent.com/15081909/46577719-43662580-c9ed-11e8-84e2-c33c5b5239bb.png)

![image](https://user-images.githubusercontent.com/15081909/46577716-3a755400-c9ed-11e8-924a-0af4de797a9d.png)

**Comment by JonnyWong16** [comment] 2018-10-07 02:59
You need the show's rating key.

**Comment by Jeeaaasus** [comment] 2018-10-07 03:00
And what should I input as new rating key?

**Comment by JonnyWong16** [comment] 2018-10-07 03:00
If the show level rating key hasn't changed inside the Tautulli database, then just enter the same number.

**Comment by Jeeaaasus** [comment] 2018-10-07 03:05
I dont think it's gotten a new rating key for the show, but I'm not sure.. I only see one jack ryan in my library
![image](https://user-images.githubusercontent.com/15081909/46577778-9c828900-c9ee-11e8-92bc-3403d021d4e6.png)


Same "Updated metadata in database."
![image](https://user-images.githubusercontent.com/15081909/46577764-588f8400-c9ee-11e8-8b74-8ecbe10fc95c.png)

Nothing changed.

**Comment by JonnyWong16** [comment] 2018-10-07 03:07
Then it's probably not updating because you have one episode already listed under two different rating keys in the database. You will have to manually edit the database if you want to fix it.

I'm closing this issue because this is not a bug report.

**Closed by JonnyWong16** 2018-10-07 03:07 UTC

**Comment by JonnyWong16** [comment] 2018-10-07 03:16
Or try switching to the `nightly` branch. Reverse sorting might do the trick. 4302c4bc0dcf2762cb4937dbfe98ed1c81d03be1

**Comment by Jeeaaasus** [comment] 2018-10-07 03:17
I'm going to delete the show from plex and re-add it and then hopefully it works, Thanks for your help :)

**Comment by JonnyWong16** [comment] 2018-10-07 03:18
That will just make it even worse...
