### ISSUE TITLE
Newsletter HTML file not being generated

### ISSUE THREAD

**Issue by nwithan8** [Tautulli/Tautulli-Issues#271] opened 2020-08-14 16:54 UTC
**Describe the Bug**
New newsletter HTML files are not being generated. Issue arose about a month ago (possibly due to Python 3 migration?).
"Newsletter logs" do not indicate an issue, "Tautulli Logs" do. HTML file missing in directory.
No other issues with Tautulli, no modifications to directory read-write settings.

**Steps to Reproduce**
1. Go to "Settings" -> "Newsletter Agents". Create an agent, then hit "Test Newsletter" -> "Test Recently Added Newsletter".
2. Go to "View Logs" -> "Newsletter Logs". Newsletter will appear as an entry, suggesting it sent.
3. Go to "Tautulli Logs" and see entry: Tautulli NewsletterHandler :: Newsletter file 'newsletter_******.html' is missing.
4. Go to Tautulli's root directory -> "newsletters", see that file is in fact missing.

**Expected Behavior**
HTML file to be generated and sent using the indicated notifier.
On failure, for a log entry in "Newsletter Logs" to indicate that it failed to render.

**Screenshots**
![image](https://user-images.githubusercontent.com/17054780/90272986-38238280-de2c-11ea-8b50-84e748655da3.png)
![image](https://user-images.githubusercontent.com/17054780/90273041-50939d00-de2c-11ea-88e5-d4911cd57ae1.png)
![image](https://user-images.githubusercontent.com/17054780/90273106-6a34e480-de2c-11ea-8025-276a901693f6.png)
Weekly newsletter began failing in mid-July

**Relevant Settings**
Using Discord webhook and email notification agents, both failing because file is empty.
![image](https://user-images.githubusercontent.com/17054780/90273269-b2ec9d80-de2c-11ea-9f43-c65024ec813f.png)

**Tautulli and System Info (see Tautulli settings page)**
Git Branch: master
Git Commit Hash: v2.5.4
Configuration File: /config/config.ini
Database File: /config/tautulli.db \| Status
Log File: /config/logs/tautulli.log
Backup Directory: /config/backups
Cache Directory: /config/cache
Newsletter Directory: /config/newsletters
Arguments: ['--datadir', '/config']
Platform: [Docker] Linux 4.19.107-Unraid (#1 SMP Tue May 12 21:21:40 BST 2020)
System Timezone: America/New_York (UTC-0400)
Python Version: 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]

**Link to logs (required)**
https://gist.github.com/nwithan8/b92b105a23178162d1007633bbe90e32
Relevant Error: https://gist.github.com/nwithan8/b92b105a23178162d1007633bbe90e32#file-tautulli_logs_20200814-L6586

**Comment by JonnyWong16** [comment] 2020-08-14 16:59
Are you using a custom newsletter template?

```
2020-08-14 12:32:59 - ERROR   :: Thread-1 : Tautulli Newsletters :: Recently Added newsletter failed to render template. Newsletter not sent.
```

**Comment by nwithan8** [comment] 2020-08-14 17:07
Yes, I am. I have a ``recently_added.html`` file in the folder indicated in settings (/config is /mnt/user/appdata/plexpy because this is Docker).
![image](https://user-images.githubusercontent.com/17054780/90274732-1081e980-de2f-11ea-8bad-6688d57717fb.png)
![image](https://user-images.githubusercontent.com/17054780/90274754-1bd51500-de2f-11ea-9245-0331cefab1c0.png)

**Comment by JonnyWong16** [comment] 2020-08-14 17:15
Does it work if you clear the "Custom Newsletter Templates Folder"?

**Comment by nwithan8** [comment] 2020-08-14 17:25
Yes, with "Custom Newsletter Templates Folder" empty, the newsletter rendered and was sent properly.

So I guess the issue narrows to "newsletter templates are broken"

**Comment by JonnyWong16** [comment] 2020-08-14 17:27
The issue is with your custom template file. You need to make sure it's up-to-date to work with Tautulli. You can see the changes that have been made to the master template [here](https://github.com/Tautulli/Tautulli/commits/master/data/interfaces/newsletters/recently_added.html) so that you can replicate them on your template.

This is not a Tautulli bug so I am closing this issue.

**Closed by JonnyWong16** 2020-08-14 17:27 UTC
