### ISSUE TITLE
"Home" doesn´t update after pre-roll

### ISSUE THREAD

**Issue by nitrox-github** [Tautulli/Tautulli-Issues#197] opened 2019-10-03 17:41 UTC
**Describe the Bug**
I added some pre-rolls to PMS. Tautulli shows which pre-roll is played but doesn´t update "Home" afterwards. So the info/statistics of the movie is missing. Reloading "Home" fixes it.

**Steps to Reproduce**
1. Add pre-rolls to current PMS, version doesn´t matter, same on 1.17.xx and 1.18.xx.

**Expected Behavior**
Update "Home" after pre-roll has played, show info/stats on movie.

**Screenshots**
![tautulli-plex-pre-roll](https://user-images.githubusercontent.com/8950340/66150461-85807200-e615-11e9-8355-5fb5b284381b.PNG)

**Relevant Settings**
- nothing special

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.1.34
- Git Branch: master
- Git Commit Hash: 08714436c3a7665abeb621b9fe52cc8b779c5473
- Platform and Version: debian
- Python Version: 2.7.16+ (default, Sep 4 2019, 08:19:57) [GCC 9.2.1 20190827]
- Browser and Version: Firefox 69

**Link to logs (required)**
- none available

**Comment by Arcanemagus** [comment] 2019-10-03 17:57
This is unfortunately a Plex bug that we have no control over.

**Comment by Arcanemagus** [comment] 2019-10-03 17:57
Duplicate of #96

**Closed by Arcanemagus** 2019-10-03 17:57 UTC
