### ISSUE TITLE
Strange issue with PlayTotals graph being generated - Months missing/duplicated

### ISSUE THREAD

**Issue by cathal00** [Tautulli/Tautulli-Issues#126] opened 2018-10-02 08:59 UTC
VERSION V2.1.21
master
Commit Hash: c8575bbc0fb7091e92f316628940acf3790f04da
Linux 4.4.0-134-generic (#160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 - Ubuntu 16.04 xenial)
Python 2.7.12

I noticed two days ago that when looking at the 'PlayTotals' tab on the 'Graphs' page that some months were duplicated and others were not shown at all. I have been using PlexPy for over two years but this is the first time i noticed this occurring.

You can see in the below screenshot that October 2017 is listed twice and March 2018 does not show at all.
![15 months](https://user-images.githubusercontent.com/43776337/46338563-662cbe80-c628-11e8-8ee4-c79509ea1815.png)

Also when the range of months is selected to be 12 or less, A month is missing and the first month 
 listed shows with 0 play time which is incorrect.

You can see from this screenshot that October 2017 is incorrectly listed with 0hr playtime and again March 2018 is missing.
![12 month](https://user-images.githubusercontent.com/43776337/46338562-65942800-c628-11e8-9970-de58a362e1b9.png)

I pulled a fresh copy of PlexPy 2.1.21 on the same server with no config but the same DB, running on a different port. When accessing this clean instance of plexpy, the issue remains.

I also pulled a fresh copy of 2.1.21 on a Win10 PC which I previously used as a Plex server. On that windows 10 instance the graph displayed correctly which seems very odd to me.

EDIT: Just spun up fresh ubuntu server VM, installed Tautulli 2.1.21 and python and placed my db file in the Tautulli directory. Browsed to VM:8181/graphs and issue remains.

The issue is easily repeatable when running plexpy on Ubuntu 16.04 when using my DB.
A fresh instance of plexpy without config will still show the graph incorrectly. I'm happy to provide my config/DB to anyone who wants to take look.

All other graphs display correctly - Data for March 2018 is present in DB even though its not displayed.

No errors are listed in the logs that i could find so i will not bother to post them. If someone thinks they will help let me know.

Not a serious issue but any help is appreciated.

Cathal.

**Comment by JonnyWong16** [comment] 2018-10-02 13:14
You have an incorrect time or timezone on your Ubuntu server.

**Comment by cathal00** [comment] 2018-10-02 13:40
I just double checked and the time/date is definitely correct and automatically set from the internet.

![2018-10-02 14_38_00-plex-server ubuntu - teamviewer - free license non-commercial use only](https://user-images.githubusercontent.com/43776337/46352169-0ac2f680-c651-11e8-8559-b1b9490525c9.png)
.

**Comment by JonnyWong16** [comment] 2018-10-06 03:30
Can you run this SQL query on your database?

```sql
SELECT strftime("%Y-%m", datetime(started, "unixepoch", "localtime")) AS datestring,
  SUM(CASE WHEN media_type = "episode" AND stopped > 0 THEN (stopped - started)
	- (CASE WHEN paused_counter IS NULL THEN 0 ELSE paused_counter END) ELSE 0 END) AS tv_count,
  SUM(CASE WHEN media_type = "movie" AND stopped > 0 THEN (stopped - started)
	- (CASE WHEN paused_counter IS NULL THEN 0 ELSE paused_counter END) ELSE 0 END) AS movie_count,
  SUM(CASE WHEN media_type = "track" AND stopped > 0 THEN (stopped - started)
	- (CASE WHEN paused_counter IS NULL THEN 0 ELSE paused_counter END) ELSE 0 END) AS music_count
FROM session_history
GROUP BY strftime("%Y-%m", datetime(started, "unixepoch", "localtime"))
ORDER BY datestring DESC
```

**Comment by JonnyWong16** [comment] 2018-10-08 14:12
I don't know what the issue is (I'm still convinced it has to do with your system time/timezone), but this is definitely an issue with your Ubuntu server. Your database is fine and you have already proven that it is fine on Windows. There is nothing more I can do.

**Comment by cathal00** [comment] 2018-10-09 10:09
I did some further testing on the Ubuntu server VM.

I ran dpkg-reconfigure tzdata to confirm that the timezone was correct (Dublin IST) and automatically set from the internet - and the graph was displaying incorrectly as before.
![dublin timezone](https://user-images.githubusercontent.com/43776337/46662194-ab199d80-cbb2-11e8-996e-74e7b90dda1e.png)


I then re-ran n dpkg-reconfigure tzdata and randomly selected a new timezone (Arctic time CEST) and the graph began to display correctly.
![arctic](https://user-images.githubusercontent.com/43776337/46659018-f2e8f680-cbab-11e8-980d-3705acde12f1.png)


If i change the timezone back to Dublin IST, the graph breaks again.

I've tried many timezones but Dublin - Irish Standard Time (UTC +1) is the only one that causes the Graph to break that i have found.

Setting it to London - British Summer Time (Currently also UTC + 1) displays the graph without issue, 

I have now tested this on my Ubuntu Desktop 16.04 main server, and clean Ubuntu Server 16.04 VM.
I also created a Ubuntu Desktop 18.04 VM on a different Windows PC.
All 3 Linux installations demonstrate the same behaviour/error only when set to the correct timezone of Irish Standard Time.

Any idea what could be causing this? Two of these are fresh OS installations so there shouldn't be any issues with configuration. All 3 installations have a clean pull of Tautulli and display the same error even when using a clean configuration file.

Changing any of the 3 operating systems away from IST displays the graph correctly, but i would rather keep the correct timezone on the server.

Any thoughts?

**Comment by JonnyWong16** [comment] 2018-10-09 15:32
You're on your own. This is with a clean docker container set to `TZ=Europe/Dublin`.

![image](https://user-images.githubusercontent.com/9099342/46680319-af878b80-cb9d-11e8-8be1-122b46afad24.png)

Closing this issue because it is not a bug report.

**Closed by JonnyWong16** 2018-10-09 15:32 UTC

**Comment by cathal00** [comment] 2018-10-10 12:41
Fair enough, I understand your point.

I'm not sure what other steps i could take considering i have replicated the issue on multiple clean Ubuntu installations a with clean Tautulli Pulls.
