### ISSUE TITLE
Incorrect time zone in history

### ISSUE THREAD

**Issue by goose-ws** [Tautulli/Tautulli-Issues#121] opened 2018-09-15 22:55 UTC
**Version:**
`v2.1.20`

**Branch:**
`master`

**Commit hash:**
`4944ce1ca05af75efd8ad5df30cf537ae43bace0`

**Operating system:**
`Linux 4.9.0-5-amd64 (#1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) - debian 9.3)`

**Python version:**
`2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`

**What you did?**
Viewed items in the `History` tab.

**What happened?**
Times appear to be displayed in the UTC time zone, as opposed to the EST time zone set in `/etc/timezone` and as shown properly by `date`.

**What you expected?**
Times to appear in the correct time zone.

**How can we reproduce your issue?**
Set the server time to EST, then view the `History` log after an item has been entered into its log.

**What are your (relevant) settings?**
My `/etc/timezone` shows `US/Eastern`

**Link to logs:**
n/a I think? I'll be happy to provide them in requested.

**Comment by Arcanemagus** [comment] 2018-09-15 23:10
You need to look into why your Python installation isn't getting that timezone setting then, you can check what it is reporting with this:

```
> python
>>> import datetime
>>> print(datetime.datetime.now())
```

Closing this as issues are not the place for support requests. If you can't find the cause of this misconfiguration on your own feel free to use one of the [support options](https://tautulli.com/#support) for some help, with the [Discord server](https://tautulli.com/discord) being preferred.

Thanks!

**Closed by Arcanemagus** 2018-09-15 23:10 UTC
