### ISSUE TITLE
IPv6 addresses do not show up in the activity cards

### ISSUE THREAD

**Issue by psaab** [Tautulli/Tautulli-Issues#208] opened 2019-12-19 19:12 UTC
When IPv6 addresses are used to connect to plex, you will see "..." for the IP address instead of the IPv6 address.  This only happens on desktop browsers, not on mobile phone browsers

To see an example see:
https://www.dropbox.com/s/mr1bhnn1755rucn/Screenshot%202019-12-19%2011.09.08.png?dl=0

**Comment by JonnyWong16** [comment] 2020-01-21 04:16
Cannot reproduce. I don't have IPv6 networking so I threw in a dummy address.

![image](https://user-images.githubusercontent.com/9099342/72775038-b1723400-3bc1-11ea-8cde-2cc837e10b65.png)

**Comment by psaab** [comment] 2020-01-21 15:02
Safari or chrome?  I've noticed it only happens in chrome and Firefox.
Safari it renders

**Comment by JonnyWong16** [comment] 2020-01-21 15:46
My screenshots above is from Chrome on Windows.

**Comment by JonnyWong16** [comment] 2020-03-17 19:09
Should be resolved in v.2.2.0.

**Closed by JonnyWong16** 2020-03-17 19:09 UTC
Labels: severity:minor, status:need-more-info, topic:ui
